### ISSUE TITLE
How to help

### ISSUE THREAD

**Issue by DhruvaSambrani** [bcspragu/logseq-sync#7]
I, and probably others too, would like to help. Maybe a short addendum to the readme with a bit more clarity on how we can help :)

**Comment by bcspragu** [comment]
Thanks Dhruva, I appreciate the support! I've updated the README contributing section to call out the three main areas I'd like support. The main blocker is just making sure the Logseq team is willing to accept changes to the Logseq codebase needed to support a self-hosted API, there's a few different repos + places where the current API is hardcoded.

**Comment by fivestones** [comment]
Have you reached out to the Logseq team about this already, and not gotten a response? Or is this still just something that needs to be done?

No rush, I was just wondering because no response for a long time from them feels more ominous than if you haven't approached them yet.

**Comment by fivestones** [comment]
Sorry, I just saw in the readme where you listed places you've reached out to the Logseq team and there's no response 😒 ...yet.
