### ISSUE TITLE
Why not a plugin?

### ISSUE THREAD

**Issue by gaurishhs** [bcspragu/logseq-sync#8]
Hi! 

Is it possible to have this as a plugin for Logseq instead of a self-hosted server. I think this could reduce the complexity of manipulation of Logseq application itself. Something like a S3 Sync plugin where the user could configure the S3 credentials and the syncing could happen in background. This could also be a solution for users who do not want to self-host. 

I'm opening this as an issue since Discussions is disabled.

**Comment by bcspragu** [comment]
(thanks for the heads up on Discussions being disabled, enabling and moving there)
